FROM ubuntu
WORKDIR /usr/src/
COPY ./src/* /usr/src/
RUN apt-get update && apt-get install -y build-essential python3-dev wget pip libsndfile1 ffmpeg
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN wget "https://github.com/pjsip/pjproject/archive/refs/tags/2.12.1.tar.gz" && tar -xvzf 2.12.1.tar.gz
RUN ls
RUN cd pjproject-2.12.1 && export CFLAGS="$CFLAGS -fPIC" && ./configure && make dep && make && cd pjsip-apps/src/python/ && python setup.py install
RUN pip install soundfile requests


CMD ["python", "runclient.py"]